import { Box, Grid, useTheme } from '@mui/material';
import { useEffect, useState } from 'react';

import Skeleton from '@/components/Skeleton';

import { CmsApi } from '@/api/cms-api';
import BucketIcon from '@/icons/BucketIcon';
import EarningIcon from '@/icons/EarningIcon';
import PeopleIcon from '@/icons/PeopleIcon';
import WindowsLogoIcon from '@/icons/WindowsLogoIcon';
import Analytics from '@/screen/Dashboards/Analytics';
import SaaSCard from '@/screen/Dashboards/Card';
import RecentOrders from '@/screen/Dashboards/RecentOrders';
import TopSelling from '@/screen/Dashboards/TopSelling';
import TotalSpent from '@/screen/Dashboards/TotalSpent';
import { Count } from '@/shared/types/dashboardType';
// Generated by https://quicktype.io

const Dashboard = () => {
  const theme = useTheme();
  const [count, setCount] = useState<Count>();
  const [loading, setLoading] = useState(false);

  const getCount = async () => {
    try {
      setLoading(true);
      const res = await CmsApi.getCount();
      setCount(res.data.data.count);
      setLoading(false);
    } catch (e) {
      console.log(e);
      setLoading(false);
    }
  };

  useEffect(() => {
    getCount();
  }, []);

  const cardList = [
    {
      price: count?.item_count,
      Icon: BucketIcon,
      title: 'Tổng sản phẩm',
      color: theme.palette.primary.main,
    },
    {
      price: count?.order_count,
      title: 'Tổng đơn hàng',
      Icon: EarningIcon,
      color: theme.palette.primary.purple,
    },
    {
      price: count?.total_price,
      Icon: WindowsLogoIcon,
      title: 'Tổng doanh thu',
      color: theme.palette.primary.red,
    },
    {
      price: count?.user_count,
      Icon: PeopleIcon,
      title: 'Tổng người dùng',
      color: theme.palette.primary.yellow,
    },
  ];

  return (
    <Box pt={2} pb={4}>
      <Grid container spacing={{ xs: 2, sm: 3, md: 4 }}>
        {!loading
          ? cardList.map((card, index) => (
              <Grid item lg={3} xs={6} key={index}>
                <SaaSCard card={card} />
              </Grid>
            ))
          : Array(4)
              .fill(null)
              .map((_, index) => (
                <Grid item lg={3} xs={6} key={index}>
                  <Skeleton>
                    <Box
                      sx={{
                        height: 126,
                        borderRadius: 12,
                      }}
                    />
                  </Skeleton>
                </Grid>
              ))}
      </Grid>
      <Grid container spacing={4} pt={4}>
        <Grid item lg={8} md={7} xs={12}>
          <TotalSpent />
        </Grid>
        <Grid item lg={4} md={5} xs={12}>
          <Analytics />
        </Grid>

        <Grid item lg={8} md={7} xs={12}>
          <RecentOrders />
        </Grid>
        <Grid item lg={4} md={5} xs={12}>
          <TopSelling />
        </Grid>

        {/* <Grid item xs={12}>
          <Footer imageLink='/static/illustration/sass-dashboard.svg' />
        </Grid> */}
      </Grid>
    </Box>
  );
};

export default Dashboard;
