export interface ReqItem {
  name: string;
  description: string;
  price: number | string;
  cost: number | string;
  images: string[];
  categoriesId: string[];
  quantity: number | string;
  details: string;
  stock: number | string;
  active: boolean;
}

export interface ReqSearch {
  page?: number;
  search?: string;
  sort?: string;
  take?: number;
  order?: string;
}

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ResItem {
  data: Product[];
  meta: Meta;
  message: string;
}

export interface Product {
  id: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  name: string;
  description: string;
  quantity: number;
  price: number;
  cost: number;
  images: string[];
  stock: number;
  details: string;
  sku: string;
}

export interface Meta {
  page: number;
  take: number;
  itemCount: number;
  pageCount: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
